FROM golang:1.26-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE ${APP_PORT}

CMD ["air", "-c", ".air.toml"]
