services:
  duon_db:
    image: postgres:16
    container_name: duon_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/infra/database/db-fixtures/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./internal/infra/database/db-fixtures/db-fixtures.sql:/docker-entrypoint-initdb.d/manual
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    environment:
      - TZ=America/Sao_Paulo

  duon_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: duon_api
    depends_on:
      duon_db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    environment:
      - TZ=America/Sao_Paulo
    tty: true
    stdin_open: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "9090:80"
    depends_on:
      - duon_db

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate"]

  #redis:
  #  image: redis:7
  #  container_name: app_redis
  #  ports:
  #    - "${REDIS_PORT}:6379"

  ##worker:
  ##  build: .
  ##  container_name: app_worker
  ##  depends_on:
  ##    - redis
  ##    - postgres
  ##  env_file:
  ##    - .env
  ##  command: ["./worker"]

volumes:
  postgres_data:
